#!/usr/bin/env python

Import('env')

so = env.SharedLibrary('libgdarchive.so', ['gdns.c', 'gdarchive.c'])
inst_so = env.Install("#addons/gdArchive", "#build/linux/libgdarchive.so")
env.Depends(inst_so, so)

if env['builtin_libarchive']:
	la = env.Command('addons/gdArchive/libarchive.so', '', './src/thirdparty/build.sh')
	env.Depends(so, la)
	inst_la = env.Install("#addons/gdArchive", "#src/thirdparty/libarchive.so")
	env.Depends(inst_la, so)
